### ISSUE TITLE
function Timex.Duration.now/1 is undefined (module Timex.Duration is not available)

### ISSUE THREAD

**Issue by Overbryd** [pvdvreede/pinglix#9]
I had to manually add `:timex` to `:extra_applications`, that enables Pinglix to use `Timex.Duration.now/1`.

Maybe this should be fixed here, or at least added to the README. Spent some time debugging this, as I didn't expect Pinglix causing this by a transient dependency.

```
Request: GET /_ping
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function Timex.Duration.now/1 is undefined (module Timex.Duration is not available)
        Timex.Duration.now(:seconds)
        (pinglix) lib/pinglix/status.ex:29: Pinglix.Status.set_current_time/1
        (hs_api) lib/.../ping.ex:1: Redacted.Ping.call/2
        (hs_api) lib/.../endpoint.ex:1: Redacted.Endpoint.plug_builder_call/2
        (hs_api) lib/.../endpoint.ex:1: Redacted.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /.../deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
19:42:08.307 [info] SIGTERM received - shutting down
```

**Comment by pvdvreede** [comment]
Thanks for the issue! I will add it to the extra_applications as you suggest - Ill try and do it over the xmas break.
